server:
  port: 20010
spring:
  application:
    name: client-config
  cloud:
   config:
    uri: http://localhost:10010/
    profile: default
    label: master

info:
  app:
    name: 'config-client'
  build:
    artifactId: 'config-client'
    version: '0.0.1-SNAPSHOT'
  author:
    name: 'config-client'