server:
  port: 20010
info:
  app:
    name: 'config-client'
  build:
    artifactId: 'config-client'
    version: '0.0.1-SNAPSHOT'
  author:
    name: 'config-client'

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 展示全部端点（默认展示health,info，其余均禁止）
      #CORS跨域支持
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  #health端点的访问权限
  endpoint:
    health:
      #选择展示
      show-details: always
  health:
    mail:
      enabled: false  # 不监控邮件服务器状态
