server:
  port: 2001
 
spring:
  servlet:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 20MB # 设置单个文件的最大长度
      max-request-size: 50MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  application:
    name: produce

info:
  app:
    name: @project.artifactId@
  build:
    artifactId: @project.artifactId@
    version: @project.version@
  author:
    name: begin-spring(zone:LightSnow)

eureka:
  instance:
    hostname: @project.artifactId@
    appname: produce
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    metadata-map:
     zone: AllZone #LightSnow
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: DaLian
    availability-zones:
     DaLian: AllZone,LightSnow,GreatSnow
    service-url:
      LightSnow: http://eureka-server:eureka-server@server-light-snow:1001/eureka/
      GreatSnow: http://eureka-server:eureka-server@server-great-snow:1002/eureka/
      AllZone: http://eureka-server:eureka-server@server-light-snow:1001/eureka/,http://eureka-server:eureka-server@server-great-snow:1002/eureka/
      